{% set component_name = "sensors" %}
{% set base_name = "libignition-" + component_name %}
{% set version = "6_6.0.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version.split('_')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/ignitionrobotics/ign-{{ component_name }}/archive/ignition-{{ component_name }}{{ version }}.tar.gz
    sha256: ad9da18d8d1316bccfe86e943c3f66b806cf3614bcf79479fc86c94a0c3680de

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make  # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-cmake2
    - libprotobuf
    - libignition-math6
    - libignition-common4
    - libignition-transport10
    - libignition-rendering5
    - libignition-msgs7
    - libignition-plugin1
    - libsdformat11
    - libarchive  # [osx]
    - ogre  {{ ogre }}
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/{{ component_name }}{{ major_version }}/ignition/{{ component_name }}.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-{{ component_name }}{{ major_version }}/ignition-{{ component_name }}{{ major_version }}-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\\{{ component_name }}{{ major_version }}\\ignition\\{{ component_name }}.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ignition-{{ component_name }}{{ major_version }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ignition-{{ component_name }}{{ major_version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-{{ component_name }}{{ major_version }}\\ignition-{{ component_name }}{{ major_version }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-{{ component_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Robotics library that provide numerous sensor models designed to generate realistic data from simulation environments.

extra:
  feedstock-name: {{ base_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
