azure:
  settings_osx:
    pool:
      vmImage: macOS-11
bot:
  abi_migration_branches:
  - v4
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
test: native_and_emulated
